'use strict';

/* Asset pipeline. Loads everything named in assets/manifest.js (generated by
   tools/slice_assets.py). Every accessor degrades gracefully: a missing image
   returns null and the caller falls back to the procedural draw, so the game
   always runs even with an empty assets/ folder. */

/* frames with baked label text (same orange as the flames — unkeyable) are
   skipped; procedural smoke covers the late phases instead */
const VFX_SKIP = {
  expl_5: 1, expl_6: 1, expl_7: 1, expl_8: 1,
  blast_3: 1, blast_4: 1, blast_5: 1,
  napalm_0: 1, napalm_1: 1, napalm_2: 1, napalm_3: 1, napalm_4: 1, napalm_5: 1,
  napalm_6: 1, napalm_7: 1, napalm_8: 1, napalm_9: 1, napalm_10: 1,
  napalm_11: 1, napalm_12: 1, napalm_13: 1,
};

const Assets = {
  images: {},
  anims: {},
  total: 0,
  loaded: 0,
  done: false,

  init(onProgress) {
    const man = this.manifest();
    if (!man || !man.images) { this.done = true; onProgress && onProgress(1); return; }
    const entries = Object.entries(man.images);
    this.total = entries.length;
    if (!this.total) { this.done = true; onProgress && onProgress(1); return; }
    for (const name in (man.anims || {})) {
      this.anims[name] = man.anims[name].filter(f => !VFX_SKIP[f]);
    }
    /* DEFERRED FALLBACK ART.
     *
     * Everything in the manifest used to load at boot, and a large share of it
     * is art the player will almost certainly never see: the 150 legacy vector
     * soldier sheets exist only for browsers where the 3D atlases fail, and
     * most inked terrain slices only draw when a prop is missing. Measured,
     * that is 5.9 MB of a 22.3 MB boot spent on a path that should never run.
     *
     * Entries flagged `defer` are skipped at boot and fetched on FIRST USE
     * instead — see img(). They stay in the manifest, so nothing is lost and
     * the fallback still works; it just costs a frame the first time rather
     * than costing every player several seconds up front.
     *
     * `total` counts only the eager set, so the loading bar still reaches 100%.
     */
    const eager = entries.filter(([, m]) => !m.defer);
    this.total = eager.length;
    if (!this.total) { this.done = true; onProgress && onProgress(1); return; }
    for (const [name, m] of eager) {
      const img = new Image();
      img.onload = () => { this.images[name] = img; this._tick(onProgress); };
      img.onerror = () => this._tick(onProgress);
      img.src = m.src;
    }
  },

  _tick(onProgress) {
    this.loaded++;
    if (onProgress) onProgress(this.loaded / this.total);
    if (this.loaded >= this.total) this.done = true;
  },

  manifest() {
    return (typeof ASSET_MANIFEST !== 'undefined') ? ASSET_MANIFEST : null;
  },

  /* A deferred entry starts loading the first time something asks for it, and
   * returns null until it arrives. Every caller in the game already treats a
   * null image as "fall back to the procedural draw", which is exactly the
   * right behaviour for one frame. */
  img(name) {
    const hit = this.images[name];
    if (hit) return hit;
    if (!this._pending) this._pending = {};
    if (this._pending[name]) return null;
    const man = this.manifest();
    const m = man && man.images && man.images[name];
    if (!m || !m.defer) return null;
    this._pending[name] = 1;
    const img = new Image();
    img.onload = () => { this.images[name] = img; };
    img.src = m.src;
    return null;
  },
  animMeta(name) {
    const man = this.manifest();
    return (man && man.animMeta && man.animMeta[name]) || null;
  },

  meta(name) {
    const man = this.manifest();
    return man && man.images[name] || null;
  },

  sheet(key) {
    const man = this.manifest();
    return man && man.sheets && man.sheets[key] || null;
  },

  anim(name) {
    const a = this.anims[name];
    return a && a.length ? a : null;
  },

  /* Draw an image so its recorded anchor (foot point) lands at (x, y). */
  drawAnchored(ctx, name, x, y, scale, dir = 1, alpha = 1, rot = 0) {
    const img = this.img(name), m = this.meta(name);
    if (!img || !m) return false;
    ctx.save();
    ctx.translate(x, y);
    if (rot) ctx.rotate(rot);
    ctx.scale(dir * scale, scale);
    ctx.globalAlpha = alpha;
    ctx.drawImage(img, -m.ax, -m.ay);
    ctx.restore();
    return true;
  },

  /* Draw the i-th frame of an anim centered at (x, y), height = h px. */
  drawAnimFrame(ctx, animName, i, x, y, h, opts = {}) {
    const frames = this.anim(animName);
    if (!frames) return false;
    const name = frames[Math.max(0, Math.min(frames.length - 1, i))];
    const img = this.img(name), m = this.meta(name);
    if (!img || !m) return false;
    const s = h / m.h;
    const w = m.w * s;
    ctx.save();
    if (opts.add) ctx.globalCompositeOperation = 'lighter';
    ctx.globalAlpha = opts.alpha != null ? opts.alpha : 1;
    ctx.translate(x, y);
    if (opts.flip) ctx.scale(-1, 1);
    // anchor: bottom-center for grounded FX, center for bursts
    const ay = opts.ground ? h : h / 2;
    ctx.drawImage(img, -w / 2, -ay, w, h);
    ctx.restore();
    return true;
  },
};
